<%@ Page Title="Home - LovelyCurtains Ltd" Language="C#" MasterPageFile="~/masterpages/Site.Master" AutoEventWireup="true"
    CodeBehind="Index.aspx.cs" Inherits="LovelyCurtains.Web.Index" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <meta name="description" content="LovelyCurtains Ltd" />
    <meta name="keywords" content="curtains in mauritius" />
    <link type="text/css" rel="stylesheet" href="/css/theatre.css" />
    <script type="text/javascript" src="/scripts/jquery.theatre-1.0.js"></script>
    <script type="text/javascript" src="/scripts/theatre-demo.js"></script>
    <link type="text/css" rel="stylesheet" href="/css/jquery.fancybox-1.3.4.css" />
    <script type="text/javascript" src="/scripts/jquery.easing-1.3.pack.js"></script>
    <script type="text/javascript" src="/scripts/jquery.fancybox-1.3.4.pack.js"></script>
    <script type="text/javascript" src="/scripts/mm.js"></script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cplTop" runat="server">
    <div id="homeTheatre" class="theatreDemo">
        <a href="/chrome/home/large/image21.jpg" class="zoom">
            <img src="/chrome/home/thumbnails/image21_1.jpg" style="height: 236px; width: 320px;" /></a>
        <a href="/chrome/home/large/image22.jpg" class="zoom">
            <img src="/chrome/home/thumbnails/image22_1.jpg" style="height: 236px; width: 320px;" /></a>
        <a href="/chrome/home/large/image23.jpg" class="zoom">
            <img src="/chrome/home/thumbnails/image23_1.jpg" style="height: 236px; width: 320px;" /></a>
        <a href="/chrome/home/large/image24.jpg" class="zoom">
            <img src="/chrome/home/thumbnails/image24_1.jpg" style="height: 236px; width: 320px;" /></a>
        <a href="/chrome/home/large/image25.jpg" class="zoom">
            <img src="/chrome/home/thumbnails/image25_1.jpg" style="height: 236px; width: 320px;" /></a>
        <a href="/chrome/home/large/image26.jpg" class="zoom">
            <img src="/chrome/home/thumbnails/image26_1.jpg" style="height: 236px; width: 320px;" /></a>
        <a href="/chrome/home/large/image27.jpg" class="zoom">
            <img src="/chrome/home/thumbnails/image27_1.jpg" style="height: 236px; width: 320px;" /></a>
        <a href="/chrome/home/large/image28.jpg" class="zoom">
            <img src="/chrome/home/thumbnails/image28_1.jpg" style="height: 236px; width: 320px;" /></a>
        <a href="/chrome/home/large/image29.jpg" class="zoom">
            <img src="/chrome/home/thumbnails/image29_1.jpg" style="height: 236px; width: 320px;" /></a>
        <a href="/chrome/home/large/image30.jpg" class="zoom">
            <img src="/chrome/home/thumbnails/image30_1.jpg" style="height: 236px; width: 320px;" /></a>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="cplPageContent" runat="server">
    <p>
        <span id="headline">Are you looking for luxury, affordable, made to measure curtains
            and bedspreads with matching accessories? </span>If so you’ve arrived at the
        right place. You can choose from our vast range of fabrics and styles to coordinate
        and enhance your home furnishings.
    </p>
    <p>
        Lovely Curtains specializes in providing our customers with the finest luxury room
        linens. Whether you’re decorating for the first time or giving your room a fresh
        look, you’ll find everything you need at our store.
    </p>
    <h2 class="centered">
        <span class="quality">Quality.</span><span class="luxury">Luxury.</span><span class="guaranteed">Guaranteed.</span>
    </h2>
    <p>
        We love the idea of creating beautiful rooms at the cheapest possible prices. We
        make no compromises on the outstanding quality of our curtains nor on our levels
        of customer service. We negotiate the best possible prices with the world’s most
        prestigious fabric manufacturers.
    </p>
    <p>
        Our mission at Lovely Curtains is to create a superior living environment that exceeds
        expectations and enhances quality of life.
    </p>
    <p>
        Finish your home off with our unique accessories. Your home will be the talk of
        the town!
    </p>
</asp:Content>
